.Dd $Mdocdate: July 31 2016 $
.Dt "NETWORKS.CONF" 5
.Os
.Sh NAME
.Nm networks.conf
.Nd network configuration file
.Sh DESCRIPTION
The
.Nm
file contains configuration information for
.Xr network 1 .
By default, this file is editable by members of the wheel group to make managing wireless networks easier.
.Pp
It consists of two sections:
.Bl -tag -width Ds
.It Ic [config]
containing common configuration information;
.It Ic [network]
containing specific network informations.
.El
.Pp
There can only be one
.Ar [config]
section, but as many
.Ar [network]
sections as you require.
.Pp
In the sections, the configuration format is
.Em key=value .
Do not add quotes around values.
.Sh CONFIG
Required options:
.Bl -tag -width Ds
.It Ic wlan_int
Name of the wireless interface.
.It Ic wlan_lladdr
Default link layer address (MAC address) for the wireless interface,
in the format xx:xx:xx:xx:xx:xx.
.It Ic hostname
Default DHCP hostname.
.El
.Pp
Optional options:
.Bl -tag -width Ds
.It Ic wired_int
Name of the wired interface, if you use it.
.It Ic wired_lladdr 
Default link layer address (MAC address) for the wired interface,
in the format xx:xx:xx:xx:xx:xx.
.El
.Sh NETWORK
Common options to all network types:
.Bl -tag -width Ds
.It Ic name
Name of the network. Used to connect to it.
.It Ic type
Type of network. Accepted values are:
.Em wired
(for a wired network),
.Em open
or
.Em wpa
(for a wireless network).
.It Ic ipv4
IPv4 configuration. Accepted values are:
.Em dhcp
or a
.Em CIDR address
(ie 192.168.0.10/24).
.It ic ipv4_gw
Gateway when using a static IP.
.It Ic hostname
DHCP hostname for this network.
.It Ic dns
DNS servers to use. Multiple servers are possible, separated by spaces.
If DHCP is used, the DNS servers will be used nonetheless in place of those
provided by the DHCP server. Remove if you want to use the DNS settings
provided by DHCP.
.It Ic dns_domain
Domain name for DNS searches, if needed.
.It Ic lladdr
Link layer address for this network. Accepted values are
.Em default ,
.Em random
for a random address, or a manual address in the format
.Em xx:xx:xx:xx:xx:xx .
.El
.Pp
Required option for all wireless networks:
.Bl -tag -width Ds
.It Ic nwid
The SSID of the wireless network.
.El
.Pp
Required option for WPA wireless networks:
.Bl -tag -width Ds
.It Ic wpakey
The wireless key.
.El
.Sh SEE ALSO
.Xr network 1
.Sh COPYRIGHT
.Ic network
is Copyright (C) 2016 ARClab \- Lionel Riem https://arclab.ch/
.Pp
.Ic network
is based on "wireless" which is Copyright (C) 2012 BSDGuides.org
